### ISSUE TITLE
Production Flight Checklist

### ISSUE THREAD

**Issue by mzagaja** [MAPC/youth-match-v2#136]
- [x] Setup sidekiq on production #124 
- [x] Start sidekiq with mailer and default queues
- [x] Update applicant information from production ICIMS #133
- [x] Add two missing requisitions: 2017-13258, 2017-13241 and download the information about them #134 
- [x] Update open position counts from ICIMS
- [x] Generate user accounts for all applicants #119 
- [x] Assign everyone their lottery numbers
- [x] Run job to update everyone to lottery activated in ICIMS
- [x] Grab status of whether people should be in lottery from ICIMS
- [x] Run preference list generation for the applicant universe
- [x] Zero out exempt sites from Deron's Excel File #137
- [x] Match the applicants to jobs
- [x] Update applicants to lottery matched
- [x] Email all applicants their accept/reject email
- [x] After 3 days push accept/decline to ICIMS
- [x] Update onboarding script in prod to make sure it pulls the production FTP onboarding file, and associates folks with accepted offers to their jobs.
