### ISSUE TITLE
Lottery 2 Flight Checklist

### ISSUE THREAD

**Issue by mzagaja** [MAPC/youth-match-v2#142]
- [x] Refresh Applicant Data from ICIMS
- [x] refresh user account email addresses
- [x] Get Lottery Activated Status from ICIMS
- [x] Confirm that 52974 is still in lottery activated status
- [x] Pull open positions from ICIMS (note: need folks in onboarding status to get correct numbers)
- [x] Run lottery
- [x] Confirm that waiting offers = number of open positions and people
- [x] Confirm that offer links work with new changes on staging
- [x] Send out offers
