### ISSUE TITLE
HIGH PRIORITY: BACKEND PUNCHLIST for CBO SELECTOR

### ISSUE THREAD

**Issue by arouault** [MAPC/youth-match-v2#66]
- [x] generate email to CBO partners with emails from Deron (we have these) #69
- [x] Implement Login System for CBOs #68
- [x] Send endpoint for check boxes to MG #67

**Comment by mzagaja** [comment]
Ahoy, here lies the legendary punch list. It shows up looking tiny and innocent, but behind it lurks dragons. 

The endpoint is going to be for the applicants_position object https://github.com/MAPC/youth-match-v2/blob/develop/app/models/applicants_position.rb#L4 and will need a controller added that accepts a PUT/PATCH (update action). The sensible thing to do will be to rename it to the "application" object which is much more descriptive than "applicants_position"

For the CBO login system we will follow the same pattern as for you the young people. However instead of sending them to the front end for the job picker they will go to the front end for the applicant picker. @allthesignals we will need to make sure that front end accepts the same email and token params as the job picker. Presumably authorization will be taken care of by the fact that a user without an associated applicant will not see jobs in the job picker, and a user without an associated CBO for their profile will not see applicants in the applicant picker.

The sticky wicket with this is that we currently have "rehire_sites", a one off model object we use to show youth that might be rehired. In some ways it feels like rehire_sites should evolve to simply be job sites, but it is definitely not that. It may well be better to introduce a job_sites model that can has_many positions and belongs to a user. A rake task will have to be written to populate this from some source somewhere (presumably a copy of the spreadsheet of users from Deron). The especially tricky (or potentially tedious part) is that there may be no magic to link positions to these job sites. Tomorrow's mission will be searching for one, or spending some hours manually entering it into a spreadsheet.

For the e-mail we will also follow the same pattern as we did with the previous system. A special note is that looking at Mailgun has betrayed that ERB's `<= @url >` method does not give us a link with a true HTML url, but just the text of the URL, likely the reason why Outlook wasn't making the link clickable (but GMail gives us the clickable link for free anyways, thanks Gmail!). A small tweak to this code will provide us with tracking on who clicks through to the job picker.

**Comment by allthesignals** [comment]
> For the CBO login system we will follow the same pattern as for you the young people.
Yes, should be the same pattern.

> Presumably authorization will be taken care of by the fact that a user without an associated applicant will not see jobs in the job picker, and a user without an associated CBO for their profile will not see applicants in the applicant picker.
This could be messy - should we explicitly define a `user_type`? An enum would do. Do you mean Devise authorizing specific requests? For example, an authorized youth applicant can only make GET and PATCH requests to the /positions endpoint but not the other way around? 

> "application" object
Yes, I like this - from what I understand, the only data being manipulated is for this object. 

> The sticky wicket with this is that we currently have "rehire_sites", a one off model object we use to show youth that might be rehired
I'm not quite following - does this have something to do with changes made here? https://github.com/MAPC/youth-match-v2/blob/develop/app/controllers/applicants_controller.rb#L16. Specifically, the new scope? The "rehire sites" data is a bit of a misnomer - it's actually applicant-level. The front-end groups by `site_name`. 

> It may well be better to introduce a job_sites model that can has_many positions and belongs to a user.
Possibly, I don't know if it's worth it. Maybe we can discuss more. I think this is a better long-term data structure, but for now I don't see the benefit of introducing more models? I guess I'm missing the issue.

Separately, for my issue https://github.com/MAPC/dyee-dashboard/issues/19, I will mostly be worried about authentication and the new `application` model. It sounds like once that endpoint is created, we're good.

**Comment by mzagaja** [comment]
The problem we face is that a position might be associated with many different Users for the purpose of allowing that user to see all the positions associated with their site. So envision the following:

BCYF Dorchester Community Center has two users: Bob and Joe.
It also has three positions: groundskeeper, admin assistant, and manager.

We need to relate both bob and joe to the three postiions. Our options are: has_and_belongs_to_many or has_many through. We can punt on creating a new model/object with has_and_belongs_to_many, but having just been down this road we know that has_and_belongs_to_many gives us a join table already and that changing that join table to have additional attributes is a pain later. So has_many through is the superior option. And what is that table's real reprsentation in the world? It's actually just representing a job site!

Circling back to the issue of `rehire_sites`, the reason why it's a sticky wicket is that it feels like it should be the "job_sites" model but it really isn't. It's more like an "applicants" model. It's basically only good at the one thing it does and not particularly good at being either an applicant nor a job site.

**Comment by allthesignals** [comment]
>  And what is that table's real reprsentation in the world? It's actually just representing a job site!
Gotcha! I understand this is the explanation for changing the join table model name to something along the lines of `job_site`, if I'm following... I have no opinion on what it's called, just as long as I understand the relationships for use in Ember Data. 

> It's basically only good at the one thing it does and not particularly good at being either an applicant nor a job site.
Yes. It's more like a pseudo-applicants model. But with the left outer join, that seems solved?

**Comment by mzagaja** [comment]
In regards to the last comment, I guess what I'm trying to say is that RehireSites is really just extra data that should be in the applicants table. You're right, it's solved and used with LEFT OUTER JOIN now, and then going forward I think we'll end up removing it and just adding a column to applicants.

**Comment by mzagaja** [comment]
I broke this down into 3 separate sub-issues to better keep track of each one. Links in the initial post.
